# Generated by Django 5.1.6 on 2025-02-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_customuser_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=11),
        ),
    ]
