# Generated by Django 5.1.6 on 2025-02-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('barangay-staff', 'Barangay Staff'), ('admin', 'Admin'), ('mddrmo-staff', 'MDDRMO Staff')], default='barangay-staff', max_length=20),
        ),
    ]
